# arctime 账户每日签到赚取积分

# 整个工作流的名称
name: 'home101'

on:
  # 在推送到 master 分支时会自动运行一次
  push:
    branches: 
      - master
  # 可以设定定时任务执行
  schedule:
    # UTC 0 点 30 定期执行一次，跟北京时间大概相距8小时，但因为排队可能会稍微延后半小时左右
    # 即北京时间 8 点 30 以后
    - cron: '39 13 * * *'

jobs:
  # arctime_auto_sign 为 job_id，后续如果有多个 job 可以引用  
  arctime_auto_sign:
    
    # 指定运行在哪台机器上
    runs-on: ubuntu-latest

    # 该job的操作步骤
    steps:
    # 将本仓库的代码拉取一份到虚拟环境机器上
    - name: Checkout
      uses: actions/checkout@v2
    # 配置安装 python 环境
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    # 配置安装依赖包
    - name: Install requirements
      run: pip install -r requirements.txt
    # 运行 python 脚本文件，其中的参数取 secrets 中配置的加密参数，账户名和密码
    - name: Working
      run: python arctime_auto_sign.py ${{ secrets.HOME101 }} ${{ secrets.PASSWORD }}
  
